 CREATE TABLE BRAND_INFO ( PID VARCHAR(128), PRIMARY KEY(PID) ) ;
 ALTER TABLE BRAND_INFO ADD BRAND_NAME  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD SORT_PID  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD PIC  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD CREATE_TIME  DATETIME  ;
 ALTER TABLE BRAND_INFO ADD CREATE_USER_ID  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD LAST_UP_TIME  DATETIME  ;
 ALTER TABLE BRAND_INFO ADD STATUS  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD DESCRIPTIONS  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD ORDER_NUM  INT  ;
 ALTER TABLE BRAND_INFO ADD PCODE  VARCHAR(128)  ;
 ALTER TABLE BRAND_INFO ADD PNAME  VARCHAR(128)  ;

